[build]
  command = "yarn build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

# Wildcard subdomain support
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables are set in Netlify dashboard
